### ISSUE TITLE
Wrong RJ45 pinout

### ISSUE THREAD

**Issue by JanosGit** [rasmartins/fbv2kpa#1]
Hi,

inspired by your and some other projects, I recently designed an FBV3 to USB-Serial Interface. I took the pinout described here as a starting point, however I found out that you mixed up some of the ground and negative RS485 lines in your description. Check my schematics - they should be correct:
https://github.com/JanosGit/FBV3Bridge/blob/master/Hardware/PDF%20Export/FBV-Interface_Schematics.pdf

I just wanted to let you know this, as your project was a very helpful resource for me to get started!

**Comment by rasmartins** [comment]
Hi,

Thank you very much for the info. I realized that a few months ago but never got around to fix the pinout.
